import 'package:flutter/material.dart';

import '../../core/models/screen_contract.dart';
import '../../core/utils/color_utils.dart';

Widget buildServerIcon(
  ComponentNode node,
  BuildContext context,
  Widget Function(ComponentNode) buildChild,
) {
  final name = node.props['name'] as String? ?? 'help_outline';
  final size = (node.props['size'] as num?)?.toDouble() ?? 24;
  final color = parseHexColor(node.props['color'] as String?);

  return Semantics(
    label: name,
    child: Icon(resolveIcon(name), size: size, color: color),
  );
}

/// Maps commonly used icon name strings to their [IconData] counterparts.
/// Falls back to [Icons.help_outline] for unrecognised names.
IconData resolveIcon(String name) => _iconMap[name] ?? Icons.help_outline;

const _iconMap = <String, IconData>{
  'home': Icons.home,
  'home_outlined': Icons.home_outlined,
  'person': Icons.person,
  'person_outlined': Icons.person_outlined,
  'settings': Icons.settings,
  'settings_outlined': Icons.settings_outlined,
  'search': Icons.search,
  'menu': Icons.menu,
  'close': Icons.close,
  'add': Icons.add,
  'remove': Icons.remove,
  'edit': Icons.edit,
  'delete': Icons.delete,
  'check': Icons.check,
  'check_circle': Icons.check_circle,
  'cancel': Icons.cancel,
  'arrow_back': Icons.arrow_back,
  'arrow_forward': Icons.arrow_forward,
  'chevron_left': Icons.chevron_left,
  'chevron_right': Icons.chevron_right,
  'expand_more': Icons.expand_more,
  'expand_less': Icons.expand_less,
  'star': Icons.star,
  'star_border': Icons.star_border,
  'star_half': Icons.star_half,
  'favorite': Icons.favorite,
  'favorite_border': Icons.favorite_border,
  'share': Icons.share,
  'copy': Icons.copy,
  'content_copy': Icons.content_copy,
  'visibility': Icons.visibility,
  'visibility_off': Icons.visibility_off,
  'lock': Icons.lock,
  'lock_open': Icons.lock_open,
  'notifications': Icons.notifications,
  'notifications_none': Icons.notifications_none,
  'email': Icons.email,
  'email_outlined': Icons.email_outlined,
  'phone': Icons.phone,
  'message': Icons.message,
  'chat': Icons.chat,
  'send': Icons.send,
  'attach_file': Icons.attach_file,
  'image': Icons.image,
  'camera': Icons.camera_alt,
  'photo': Icons.photo,
  'play_arrow': Icons.play_arrow,
  'pause': Icons.pause,
  'stop': Icons.stop,
  'download': Icons.download,
  'upload': Icons.upload,
  'cloud': Icons.cloud,
  'cloud_download': Icons.cloud_download,
  'cloud_upload': Icons.cloud_upload,
  'folder': Icons.folder,
  'file': Icons.insert_drive_file,
  'link': Icons.link,
  'language': Icons.language,
  'map': Icons.map,
  'location_on': Icons.location_on,
  'calendar': Icons.calendar_today,
  'schedule': Icons.schedule,
  'alarm': Icons.alarm,
  'timer': Icons.timer,
  'info': Icons.info,
  'info_outlined': Icons.info_outline,
  'warning': Icons.warning,
  'error': Icons.error,
  'error_outline': Icons.error_outline,
  'help': Icons.help,
  'help_outline': Icons.help_outline,
  'lightbulb': Icons.lightbulb,
  'thumb_up': Icons.thumb_up,
  'thumb_down': Icons.thumb_down,
  'shopping_cart': Icons.shopping_cart,
  'payment': Icons.payment,
  'credit_card': Icons.credit_card,
  'account_circle': Icons.account_circle,
  'group': Icons.group,
  'logout': Icons.logout,
  'login': Icons.login,
  'refresh': Icons.refresh,
  'sync': Icons.sync,
  'code': Icons.code,
  'bug_report': Icons.bug_report,
  'build': Icons.build,
  'dashboard': Icons.dashboard,
  'analytics': Icons.analytics,
  'trending_up': Icons.trending_up,
  'trending_down': Icons.trending_down,
  'bar_chart': Icons.bar_chart,
  'pie_chart': Icons.pie_chart,
  'dark_mode': Icons.dark_mode,
  'light_mode': Icons.light_mode,
  'wifi': Icons.wifi,
  'bluetooth': Icons.bluetooth,
  'battery_full': Icons.battery_full,
  'power': Icons.power,
  'science': Icons.science,
  'emoji_emotions': Icons.emoji_emotions,
  'celebration': Icons.celebration,
  'rocket_launch': Icons.rocket_launch,
};
